version: '3.8'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: store_Procedure@123
      MYSQL_DATABASE: store-procedure
      MYSQL_USER: hein
      MYSQL_PASSWORD: hein@123
    ports:
      - "3307:3306"